### ISSUE TITLE
Council Page: load pics faster

### ISSUE THREAD

**Issue by MaireadMaloney** [McGillEUS/mcgilleus-2019#1]

**Comment by thomashillyer** [comment]
not fixed. front page and council.html . Just run pics through https://tinyjpg.com/ and they'll be much better

**Comment by Anasshahidd21** [comment]
> not fixed. front page and council.html . Just run pics through https://tinyjpg.com/ and they'll be much better

It is done, you can try to pull from master and check it. I have updated it already, ran it through a better compressor. The updates are not yet pulled from the server.
