### ISSUE TITLE
Active tab highlight needs to be fixed

### ISSUE THREAD

**Issue by Anasshahidd21** [McGillEUS/mcgilleus-2019#27]
When clicking on another link, such as sponsors or events, the active tab must be focused, currently not in action. Needs to be fixed.

**Comment by ATahma** [comment]
It appears that the issue happens only with the council page

**Comment by Anasshahidd21** [comment]
> It appears that the issue happens only with the council page

cool, should be an easy fix, do you want to try?

**Comment by ATahma** [comment]
Done, closing the issue 
Commit: b070136f1408e7c77cab252ecf2635011c02221f
